server:
  port: ${SERVER_PORT:8081}
spring:
  security:
    oauth2:
      client:
        provider:
          openam:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: ${USER_NAME_ATTRIBUTE:preferred_username}
        registration:
          openam:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: ${SCOPE:openid}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE:password}
logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL:DEBUG}
        web:
          client:
            RestTemplate: ${LOG_LEVEL:DEBUG}