server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        provider:
          openam:
            #            Authorization URI of auth server
            authorization-uri: http://localhost:8080/realms/testrealm/protocol/openid-connect/auth
            #            Get Access token URI
            token-uri: http://localhost:8080/realms/testrealm/protocol/openid-connect/token
            #            URI to get user-info -> scopes, roles, attributes
            user-info-uri: http://localhost:8080/realms/testrealm/protocol/openid-connect/userinfo
            #            auth name is parsed from this attribute
            user-name-attribute: preferred_username
        registration:
          openam:
            client-id: testclient
            client-secret: w6Nia5BQvEH3OVcI5aMqfcjI1xzvdcqD
            scope: openid
            authorization-grant-type: password
logging:
  level:
    org:
      springframework:
        security: ${LOG_LEVEL:DEBUG}
        web:
          client:
            RestTemplate: ${LOG_LEVEL:DEBUG}